#!/bin/bash

set -e

if [[ ! -d 'src/node_modules' ]]; then
	echo 'Installing script dependencies...'
	cd src
	npm install
	cd ..
fi

if [[ $1 == "-r" ]]; then
	shift
	rebuild="yes"
else
	rebuild=""
fi

if [[ -n $rebuild ]]; then
	echo 'Building the script...'
	cd src
	npm --silent run build
	cd ..
fi

# Use --no-warnings to suppress the fs.promises ExperimentalWarning
node --no-warnings src/index.js $*
