#!/bin/bash

set -e

needsRebuild() {
	for ts in src/**/*.ts; do
		js="${ts%.*}.js"
		if [[ ! -f $js || $ts -nt $js ]]; then
			echo 'rebuild'
			return
		fi
	done
}

if [[ ! -d 'src/node_modules' ]]; then
	echo 'Installing script dependencies...'
	cd src
	npm install
	cd ..
fi

rebuild=$1

if [[ $rebuild == "-r" ]]; then
	shift
else
	rebuild=""
fi

if [[ -n $rebuild || -n $(needsRebuild) ]]; then
	echo 'Building the script...'
	cd src
	npm run build
	cd ..
fi

# Use --no-warnings to suppress the fs.promises ExperimentalWarning
node --no-warnings src/index.js $*
